spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/village?serverTimezone=GMT%2B8&useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: root121
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .html
  banner:
    image:
      location: banner.txt

mybatis-plus:
   mapper-locations: classpath:/mapper/*.xml
   global-config:
     db-config:
       id-type: auto
   configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8002

#redis配置
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    #Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 2
